sudo: false
language: node_js
node_js:
  - stable
script:
  - npm run build
branches:
  only:
   - master
before_deploy:
  - openssl aes-256-cbc -K $encrypted_26a036ce9b88_key -iv $encrypted_26a036ce9b88_iv -in id_rsa.enc -out id_rsa -d
  - chmod 600 id_rsa
  - eval `ssh-agent -s`
  - ssh-add id_rsa
  - git config --global user.name $USER_NAME
  - git config --global user.email $USER_EMAIL
deploy:
  provider: script
  script: npm run deploy
  skip_cleanup: true
  on:
    branch: master
    condition: $TRAVIS_PULL_REQUEST=false