sudo: false
language: node_js
node_js:
  - stable
script:
  - npm run build:comparisons
  - npm run build
branches:
  only:
    - master
deploy:
  provider: script
  script: deploy.sh
  skip_cleanup: true
  on:
    branch: master
    condition: $TRAVIS_PULL_REQUEST=false
before_install:
  - openssl aes-256-cbc -K $encrypted_abb82e9f191e_key -iv $encrypted_abb82e9f191e_iv
    -in id_rsa.enc -out id_rsa -d
